# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 12:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountstatus', models.CharField(default='active', max_length=50)),
                ('timezone', models.CharField(default='GMT', max_length=100)),
                ('ipblacklist', models.TextField(blank=True, max_length=2000)),
                ('numberblacklist', models.TextField(blank=True, max_length=2000)),
                ('callerId', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('onboarded', models.BooleanField(default=False)),
                ('firstpromoter_authid', models.CharField(blank=True, max_length=100, null=True)),
                ('signup_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('usagemeter_last_refreshed', models.DateTimeField(default=datetime.datetime.now)),
                ('usagemeter_seconds', models.IntegerField(default=0)),
                ('usagemeter_calls', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callmenow_uuid', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('ipaddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callmenow_uuid', models.CharField(max_length=100)),
                ('callmenow_comments', models.CharField(blank=True, max_length=100)),
                ('callmenow_status', models.CharField(max_length=100)),
                ('agentfirst_aleg_uuids', models.CharField(blank=True, max_length=500)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('plivo_aleg_call_status', models.CharField(blank=True, max_length=500)),
                ('plivo_bleg_call_status', models.CharField(blank=True, max_length=500)),
                ('plivo_aleg_hangup_cause', models.CharField(blank=True, max_length=500)),
                ('plivo_bleg_hangup_cause', models.CharField(blank=True, max_length=500)),
                ('plivo_aleg_call_id', models.CharField(blank=True, max_length=500)),
                ('plivo_bleg_call_id', models.CharField(blank=True, max_length=500)),
                ('plivo_aleg_duration', models.IntegerField(blank=True, default=0)),
                ('plivo_bleg_duration', models.IntegerField(blank=True, default=0)),
                ('plivo_aleg_bill', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('plivo_bleg_bill', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('bleg_phone_number', models.CharField(blank=True, max_length=500)),
                ('record_url', models.CharField(blank=True, max_length=500)),
                ('total_bill', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('dial_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_status', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('best_time_to_contact', models.CharField(blank=True, max_length=100)),
                ('ipaddress', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Leads')),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_plan_id', models.IntegerField()),
                ('paddle_plan_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('interval', models.CharField(default='monthly', max_length=30)),
                ('public_description', models.TextField(blank=True, max_length=1000)),
                ('private_description', models.TextField(blank=True, max_length=1000)),
                ('public', models.BooleanField(default=False)),
                ('max_minutes_per_month', models.IntegerField()),
                ('max_calls_per_month', models.IntegerField()),
                ('max_widgets', models.IntegerField()),
                ('max_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_subscription_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('cancel_url', models.CharField(max_length=200)),
                ('update_url', models.CharField(max_length=200)),
                ('next_bill_date', models.CharField(max_length=100)),
                ('override_max_minutes_per_month', models.IntegerField(default=0)),
                ('override_max_calls_per_month', models.IntegerField(default=0)),
                ('override_max_widgets', models.IntegerField(default=0)),
                ('override_max_users', models.IntegerField(default=0)),
                ('callmenow_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Plans')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('sms_missed_calls', models.BooleanField(default=False)),
                ('sms_completed_calls', models.BooleanField(default=False)),
                ('sms_new_lead', models.BooleanField(default=False)),
                ('email_missed_calls', models.BooleanField(default=True)),
                ('email_completed_calls', models.BooleanField(default=True)),
                ('email_new_lead', models.BooleanField(default=True)),
                ('email_widget_daily_reports', models.BooleanField(default=False)),
                ('email_widget_weekly_reports', models.BooleanField(default=False)),
                ('available_from', models.IntegerField(default=0)),
                ('available_to', models.IntegerField(default=24)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('currently_busy', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('greeting_text', models.CharField(blank=True, max_length=100, null=True)),
                ('call_setting', models.CharField(max_length=30)),
                ('call_algorithm', models.CharField(max_length=30)),
                ('capture_leads', models.BooleanField(default=False)),
                ('show_on_mobile', models.BooleanField(default=False)),
                ('ring_timeout', models.IntegerField(default=60)),
                ('allowed_countries', models.CharField(default='[]', max_length=1000)),
                ('locked', models.BooleanField(default=False)),
                ('appearance_showalert', models.BooleanField(default=True)),
                ('appearance_showalert_after', models.IntegerField(default=3000)),
                ('appearance_playsoundonalert', models.BooleanField(default=True)),
                ('appearance_alerttext', models.CharField(default='Hey There! Would You Like To Receive A Call From Us Right Now ?', max_length=100)),
                ('appearance_calltext', models.CharField(default='Would You Like To Receive A Call From Us Right Now ?', max_length=100)),
                ('appearance_leadtext', models.CharField(default='We Are Not Around. Please Leave Your Number To Receive A Callback Soon', max_length=100)),
                ('appearance_leadthankyoutext', models.CharField(default='Thank you, we will get in touch with you soon', max_length=100)),
                ('appearance_alert_textcolor', models.CharField(default='black', max_length=50)),
                ('appearance_alert_background', models.CharField(default='white', max_length=50)),
                ('appearance_body_textcolor', models.CharField(default='black', max_length=50)),
                ('appearance_body_background', models.CharField(default='white', max_length=50)),
                ('appearance_position', models.CharField(default='right', max_length=50)),
                ('appearance_buttonimage', models.CharField(default='button1.gif', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Widget')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='leads',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='leads',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Widget'),
        ),
        migrations.AddField(
            model_name='calls',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='calls',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Leads'),
        ),
        migrations.AddField(
            model_name='calls',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Widget'),
        ),
        migrations.AddField(
            model_name='callqueue',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='callqueue',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Widget'),
        ),
    ]
