# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_accounts_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts'),
            preserve_default=False,
        ),
    ]
