# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userprofile_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='accounttype',
            new_name='usertype',
        ),
    ]
