# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20171101_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('call_setting', models.CharField(max_length=30)),
                ('call_algorithm', models.CharField(max_length=30)),
                ('capture_leads', models.BooleanField(default=False)),
                ('show_on_mobile', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
            ],
        ),
    ]
