# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='accounttype',
            field=models.CharField(default='Free', max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='planid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='subscriptionid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
