# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='admin_notes',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_description',
            field=models.TextField(max_length=1000),
        ),
    ]
