# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20171102_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='admin_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
