# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20171102_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='price_inr',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='price_usd',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
