# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='timezone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
