# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_accounts_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='timezone',
            field=models.CharField(default='GMT', max_length=100),
        ),
    ]
