# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20171105_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='domainblacklist',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ipblacklist',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
