# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20171105_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='domainblacklist',
            new_name='numberblacklist',
        ),
    ]
