# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20171105_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
