# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_userprofile_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgetId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
