# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_widgetagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_status', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('best_time_to_contact', models.TimeField()),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
                ('widgetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Widget')),
            ],
        ),
    ]
