# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='widget',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leads',
            name='best_time_to_contact',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leads',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
