# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20171110_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callmenow_uuid', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('widget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Widget')),
            ],
        ),
    ]
