# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_callqueue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='busy',
            new_name='locked',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currently_busy',
            field=models.BooleanField(default=False),
        ),
    ]
