# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_callqueue_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callmenow_uuid', models.CharField(max_length=100)),
                ('callmenow_comments', models.CharField(blank=True, max_length=100)),
                ('callmenow_status', models.CharField(max_length=100)),
                ('agentfirst_aleg_uuids', models.CharField(blank=True, max_length=500)),
                ('plivo_aleg_call_status', models.CharField(blank=True, max_length=500)),
                ('plivo_bleg_call_status', models.CharField(blank=True, max_length=500)),
                ('plivo_aleg_call_id', models.CharField(blank=True, max_length=500)),
                ('plivo_bleg_call_id', models.CharField(blank=True, max_length=500)),
                ('plivo_bleg_status', models.CharField(blank=True, max_length=500)),
                ('plivo_aleg_duration', models.IntegerField(blank=True)),
                ('plivo_aleg_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('plivo_bleg_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Leads')),
                ('widget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Widget')),
            ],
        ),
    ]
