# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20171110_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls',
            name='plivo_bleg_status',
        ),
    ]
