# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20171111_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='plivo_bleg_duration',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
