# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_calls_plivo_bleg_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='bleg_phone_number',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
