# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_calls_bleg_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='agent_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
