# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_calls_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='agent_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
