# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20171111_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='record_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
