# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_calls_record_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_owner',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
            preserve_default=False,
        ),
    ]
