# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20171118_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
