# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_leads_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
