# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_callqueue_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('leadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Leads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile')),
            ],
        ),
    ]
