# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
