# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20171120_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='accountId',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='leads',
            old_name='lead_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='leads',
            old_name='widgetId',
            new_name='widget',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='accountid',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='widgetagent',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='widgetagent',
            old_name='widgetId',
            new_name='widget',
        ),
    ]
