# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20171120_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='leadId',
            new_name='lead',
        ),
    ]
