# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20171120_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callqueue',
            old_name='widget_id',
            new_name='widget',
        ),
        migrations.RenameField(
            model_name='calls',
            old_name='lead_id',
            new_name='lead',
        ),
        migrations.RenameField(
            model_name='calls',
            old_name='widget_id',
            new_name='widget',
        ),
        migrations.RemoveField(
            model_name='callqueue',
            name='agent_id',
        ),
        migrations.AddField(
            model_name='callqueue',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
        ),
    ]
