# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_auto_20171120_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls',
            name='agent_id',
        ),
        migrations.AddField(
            model_name='calls',
            name='agent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
        ),
    ]
