# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20171120_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserProfile'),
        ),
    ]
