# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_auto_20171121_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verificationcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
