# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_auto_20171123_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verificationcode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verified',
        ),
    ]
