# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_auto_20171126_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='callerId',
            field=models.CharField(default=919999199199, max_length=30),
            preserve_default=False,
        ),
    ]
