# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_accounts_callerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='greeting_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='callerId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
