# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='allowed_countries',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
