# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_widget_allowed_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='datetime',
        ),
        migrations.AddField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
