# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_auto_20171129_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='date',
        ),
        migrations.AddField(
            model_name='leads',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
