# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_auto_20171203_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='dial_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
