# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0066_countries_dial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='appearance_buttonimage',
            field=models.CharField(default='button1.gif', max_length=50),
        ),
    ]
