# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0067_auto_20171203_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
