# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0069_auto_20171204_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='firstpromoter_authid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
