# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0071_auto_20171204_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='calls',
            new_name='max_calls_per_month',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='price_inr',
            new_name='max_minutes_per_month',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='price_usd',
            new_name='max_users',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='users',
            new_name='max_widgets',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='widgets',
            new_name='paddle_plan_id',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='plan_name',
            new_name='paddle_plan_name',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='admin_notes',
            new_name='private_description',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='account',
            new_name='callmenow_account',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='current_state',
            new_name='cancel_url',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='razorpay_subscription_id',
            new_name='next_bill_date',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='accounttype',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='planid',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='subscriptionid',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='plan_description',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='razor_pay_planid',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='planid',
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountstatus',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='plans',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='public_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='override_max_calls_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='override_max_minutes_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='override_max_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='override_max_widgets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='paddle_subscription_id',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Plans'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='status',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='update_url',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
