# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0072_auto_20171204_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='callmenow_account',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
