# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0073_auto_20171204_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_plan_id', models.IntegerField()),
                ('paddle_plan_name', models.CharField(max_length=100)),
                ('public_description', models.TextField(blank=True, max_length=1000)),
                ('private_description', models.TextField(blank=True, max_length=1000)),
                ('public', models.BooleanField(default=False)),
                ('max_minutes_per_month', models.IntegerField()),
                ('max_calls_per_month', models.IntegerField()),
                ('max_widgets', models.IntegerField()),
                ('max_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_subscription_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('cancel_url', models.CharField(max_length=100)),
                ('update_url', models.CharField(max_length=100)),
                ('next_bill_date', models.CharField(max_length=100)),
                ('override_max_minutes_per_month', models.IntegerField(default=0)),
                ('override_max_calls_per_month', models.IntegerField(default=0)),
                ('override_max_widgets', models.IntegerField(default=0)),
                ('override_max_users', models.IntegerField(default=0)),
                ('callmenow_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Plans')),
            ],
        ),
    ]
