# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0074_plans_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='firstpromoter_authid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
