# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0075_auto_20171204_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='interval',
            field=models.CharField(default='monthly', max_length=30),
        ),
        migrations.AddField(
            model_name='plans',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10),
        ),
    ]
