# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0076_auto_20171204_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='cancel_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='update_url',
            field=models.CharField(max_length=200),
        ),
    ]
