# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0077_auto_20171205_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='signup_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='accounts',
            name='usagemeter_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='usagemeter_last_refreshed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='accounts',
            name='usagemeter_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
