# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0078_auto_20171205_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='usagemeter_calls',
            field=models.IntegerField(default=0),
        ),
    ]
